### PR TITLE
Portmaster: Resolve CI/CD styling failure

### PR DESCRIPTION
**Pull request by Sntx626**
Resolve CI/CD styling failure

### CODE REVIEW

**Comment by nyabinary** [comment]
Can't be rebased and merged currently because of conflicts :P

**Comment by Sntx626** [comment]
It's fine for me to drop this PR if you could run nixfmt on the portmaster module.

**Comment by nyabinary** [comment]
@Sntx626 do you have a matrix? We should probably have real-time communication, we need to make some changes now because Portmaster new UI uses Tauri instead of Electron.

**Comment by Sntx626** [comment]
I agree with you, it's cumbersome to chat through PR comments.

You can somewhat reliably catch me on matrix @sntx:matrix.org .

I think we opened up an empty chat a while ago.
I just send that contact a message.

If you didn't receive one, feel free to let me know or just message me on matrix.

**Pull request closed without merging**
